config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'tables/current_status' => 'tables#current_status'

  resources :product_modifiers

  resources :payment_audits

  resources :payments

  resources :order_audits

  resources :order_audirs

  resources :order_line_modifiers

  resources :modifiers

  resources :order_lines

  resources :orders

  resources :tables

  resources :products

end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
	has_many :product_modifiers
	has_many :products, through: :product_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :table
  has_many :order_lines
  has_many :products, through: :order_lines

  scope :open, -> { where(:status==:open)}

end

app/models/order_audir.rb
class OrderAudir < ActiveRecord::Base
  belongs_to :order
end

app/models/order_audit.rb
class OrderAudit < ActiveRecord::Base
  belongs_to :order
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :quantity
end

app/models/order_line_modifier.rb
class OrderLineModifier < ActiveRecord::Base
  belongs_to :order_line
  belongs_to :modifier
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
end

app/models/payment_audit.rb
class PaymentAudit < ActiveRecord::Base
  belongs_to :payment
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :order_lines
	has_many :orders, through: :order_lines

	has_many :product_modifiers
	has_many :modifiers, through: :product_modifiers
end

app/models/product_modifier.rb
class ProductModifier < ActiveRecord::Base
  belongs_to :product
  belongs_to :modifier
end

app/models/table.rb
class Table < ActiveRecord::Base
	has_many :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/order_line_modifiers_controller.rb
class OrderLineModifiersController < ApplicationController
  before_action :set_order_line_modifier, only: [:show, :edit, :update, :destroy]

  # GET /order_line_modifiers
  # GET /order_line_modifiers.json
  def index
    @order_line_modifiers = OrderLineModifier.all
  end

  # GET /order_line_modifiers/1
  # GET /order_line_modifiers/1.json
  def show
  end

  # GET /order_line_modifiers/new
  def new
    @order_line_modifier = OrderLineModifier.new
  end

  # GET /order_line_modifiers/1/edit
  def edit
  end

  # POST /order_line_modifiers
  # POST /order_line_modifiers.json
  def create
    @order_line_modifier = OrderLineModifier.new(order_line_modifier_params)

    respond_to do |format|
      if @order_line_modifier.save
        format.html { redirect_to @order_line_modifier, notice: 'Order line modifier was successfully created.' }
        format.json { render :show, status: :created, location: @order_line_modifier }
      else
        format.html { render :new }
        format.json { render json: @order_line_modifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_line_modifiers/1
  # PATCH/PUT /order_line_modifiers/1.json
  def update
    respond_to do |format|
      if @order_line_modifier.update(order_line_modifier_params)
        format.html { redirect_to @order_line_modifier, notice: 'Order line modifier was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line_modifier }
      else
        format.html { render :edit }
        format.json { render json: @order_line_modifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_line_modifiers/1
  # DELETE /order_line_modifiers/1.json
  def destroy
    @order_line_modifier.destroy
    respond_to do |format|
      format.html { redirect_to order_line_modifiers_url, notice: 'Order line modifier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line_modifier
      @order_line_modifier = OrderLineModifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_modifier_params
      params.require(:order_line_modifier).permit(:order_line_id, :modifier_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modifiers_helper.rb
module ModifiersHelper
end

app/helpers/order_audits_helper.rb
module OrderAuditsHelper
end

app/helpers/order_line_modifiers_helper.rb
module OrderLineModifiersHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/order_line_modifiers/_form.html.erb
<%= form_for(@order_line_modifier) do |f| %>
  <% if @order_line_modifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line_modifier.errors.count, "error") %> prohibited this order_line_modifier from being saved:</h2>

      <ul>
      <% @order_line_modifier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_line_id %><br>
    <%= f.text_field :order_line_id %>
  </div>
  <div class="field">
    <%= f.label :modifier_id %><br>
    <%= f.text_field :modifier_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_line_modifiers/edit.html.erb
<h1>Editing Order Line Modifier</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line_modifier %> |
<%= link_to 'Back', order_line_modifiers_path %>

app/views/order_line_modifiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Line Modifiers</h1>

<table>
  <thead>
    <tr>
      <th>Order line</th>
      <th>Modifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_line_modifiers.each do |order_line_modifier| %>
      <tr>
        <td><%= order_line_modifier.order_line %></td>
        <td><%= order_line_modifier.modifier %></td>
        <td><%= link_to 'Show', order_line_modifier %></td>
        <td><%= link_to 'Edit', edit_order_line_modifier_path(order_line_modifier) %></td>
        <td><%= link_to 'Destroy', order_line_modifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order line modifier', new_order_line_modifier_path %>

app/views/order_line_modifiers/new.html.erb
<h1>New Order Line Modifier</h1>

<%= render 'form' %>

<%= link_to 'Back', order_line_modifiers_path %>

app/views/order_line_modifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order line:</strong>
  <%= @order_line_modifier.order_line %>
</p>

<p>
  <strong>Modifier:</strong>
  <%= @order_line_modifier.modifier %>
</p>

<%= link_to 'Edit', edit_order_line_modifier_path(@order_line_modifier) %> |
<%= link_to 'Back', order_line_modifiers_path %>