config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'tables/current_status' => 'tables#current_status'

  resources :product_modifiers

  resources :payment_audits

  resources :payments

  resources :order_audits

  resources :order_audirs

  resources :order_line_modifiers

  resources :modifiers

  resources :order_lines

  resources :orders

  resources :tables

  resources :products

end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
	has_many :product_modifiers
	has_many :products, through: :product_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :table
  has_many :order_lines
  has_many :products, through: :order_lines

  scope :open, -> { where(:status==:open)}

end

app/models/order_audir.rb
class OrderAudir < ActiveRecord::Base
  belongs_to :order
end

app/models/order_audit.rb
class OrderAudit < ActiveRecord::Base
  belongs_to :order
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :quantity
end

app/models/order_line_modifier.rb
class OrderLineModifier < ActiveRecord::Base
  belongs_to :order_line
  belongs_to :modifier
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
end

app/models/payment_audit.rb
class PaymentAudit < ActiveRecord::Base
  belongs_to :payment
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :order_lines
	has_many :orders, through: :order_lines

	has_many :product_modifiers
	has_many :modifiers, through: :product_modifiers
end

app/models/product_modifier.rb
class ProductModifier < ActiveRecord::Base
  belongs_to :product
  belongs_to :modifier
end

app/models/table.rb
class Table < ActiveRecord::Base
	has_many :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/payment_audits_controller.rb
class PaymentAuditsController < ApplicationController
  before_action :set_payment_audit, only: [:show, :edit, :update, :destroy]

  # GET /payment_audits
  # GET /payment_audits.json
  def index
    @payment_audits = PaymentAudit.all
  end

  # GET /payment_audits/1
  # GET /payment_audits/1.json
  def show
  end

  # GET /payment_audits/new
  def new
    @payment_audit = PaymentAudit.new
  end

  # GET /payment_audits/1/edit
  def edit
  end

  # POST /payment_audits
  # POST /payment_audits.json
  def create
    @payment_audit = PaymentAudit.new(payment_audit_params)

    respond_to do |format|
      if @payment_audit.save
        format.html { redirect_to @payment_audit, notice: 'Payment audit was successfully created.' }
        format.json { render :show, status: :created, location: @payment_audit }
      else
        format.html { render :new }
        format.json { render json: @payment_audit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_audits/1
  # PATCH/PUT /payment_audits/1.json
  def update
    respond_to do |format|
      if @payment_audit.update(payment_audit_params)
        format.html { redirect_to @payment_audit, notice: 'Payment audit was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_audit }
      else
        format.html { render :edit }
        format.json { render json: @payment_audit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_audits/1
  # DELETE /payment_audits/1.json
  def destroy
    @payment_audit.destroy
    respond_to do |format|
      format.html { redirect_to payment_audits_url, notice: 'Payment audit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_audit
      @payment_audit = PaymentAudit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_audit_params
      params.require(:payment_audit).permit(:payment_id, :amount_from, :amount_to, :payment_type_from, :payment_type_to, :datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modifiers_helper.rb
module ModifiersHelper
end

app/helpers/order_audits_helper.rb
module OrderAuditsHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payment_audits_helper.rb
module PaymentAuditsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/payment_audits/_form.html.erb
<%= form_for(@payment_audit) do |f| %>
  <% if @payment_audit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_audit.errors.count, "error") %> prohibited this payment_audit from being saved:</h2>

      <ul>
      <% @payment_audit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment_id %><br>
    <%= f.text_field :payment_id %>
  </div>
  <div class="field">
    <%= f.label :amount_from %><br>
    <%= f.text_field :amount_from %>
  </div>
  <div class="field">
    <%= f.label :amount_to %><br>
    <%= f.text_field :amount_to %>
  </div>
  <div class="field">
    <%= f.label :payment_type_from %><br>
    <%= f.text_field :payment_type_from %>
  </div>
  <div class="field">
    <%= f.label :payment_type_to %><br>
    <%= f.text_field :payment_type_to %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_audits/edit.html.erb
<h1>Editing Payment Audit</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_audit %> |
<%= link_to 'Back', payment_audits_path %>

app/views/payment_audits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payment Audits</h1>

<table>
  <thead>
    <tr>
      <th>Payment</th>
      <th>Amount from</th>
      <th>Amount to</th>
      <th>Payment type from</th>
      <th>Payment type to</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_audits.each do |payment_audit| %>
      <tr>
        <td><%= payment_audit.payment %></td>
        <td><%= payment_audit.amount_from %></td>
        <td><%= payment_audit.amount_to %></td>
        <td><%= payment_audit.payment_type_from %></td>
        <td><%= payment_audit.payment_type_to %></td>
        <td><%= payment_audit.datetime %></td>
        <td><%= link_to 'Show', payment_audit %></td>
        <td><%= link_to 'Edit', edit_payment_audit_path(payment_audit) %></td>
        <td><%= link_to 'Destroy', payment_audit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment audit', new_payment_audit_path %>

app/views/payment_audits/new.html.erb
<h1>New Payment Audit</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_audits_path %>

app/views/payment_audits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment:</strong>
  <%= @payment_audit.payment %>
</p>

<p>
  <strong>Amount from:</strong>
  <%= @payment_audit.amount_from %>
</p>

<p>
  <strong>Amount to:</strong>
  <%= @payment_audit.amount_to %>
</p>

<p>
  <strong>Payment type from:</strong>
  <%= @payment_audit.payment_type_from %>
</p>

<p>
  <strong>Payment type to:</strong>
  <%= @payment_audit.payment_type_to %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @payment_audit.datetime %>
</p>

<%= link_to 'Edit', edit_payment_audit_path(@payment_audit) %> |
<%= link_to 'Back', payment_audits_path %>