config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'tables/current_status' => 'tables#current_status'

  resources :product_modifiers

  resources :payment_audits

  resources :payments

  resources :order_audits

  resources :order_audirs

  resources :order_line_modifiers

  resources :modifiers

  resources :order_lines

  resources :orders

  resources :tables

  resources :products

end

app/models/modifier.rb
class Modifier < ActiveRecord::Base
	has_many :product_modifiers
	has_many :products, through: :product_modifiers
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :table
  has_many :order_lines
  has_many :products, through: :order_lines

  scope :open, -> { where(:status==:open)}

end

app/models/order_audir.rb
class OrderAudir < ActiveRecord::Base
  belongs_to :order
end

app/models/order_audit.rb
class OrderAudit < ActiveRecord::Base
  belongs_to :order
end

app/models/order_line.rb
class OrderLine < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :quantity
end

app/models/order_line_modifier.rb
class OrderLineModifier < ActiveRecord::Base
  belongs_to :order_line
  belongs_to :modifier
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :order
end

app/models/payment_audit.rb
class PaymentAudit < ActiveRecord::Base
  belongs_to :payment
end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :order_lines
	has_many :orders, through: :order_lines

	has_many :product_modifiers
	has_many :modifiers, through: :product_modifiers
end

app/models/product_modifier.rb
class ProductModifier < ActiveRecord::Base
  belongs_to :product
  belongs_to :modifier
end

app/models/table.rb
class Table < ActiveRecord::Base
	has_many :orders
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/order_lines_controller.rb
class OrderLinesController < ApplicationController
  before_action :set_order_line, only: [:show, :edit, :update, :destroy]

  # GET /order_lines
  # GET /order_lines.json
  def index
    @order_lines = OrderLine.all
  end

  # GET /order_lines/1
  # GET /order_lines/1.json
  def show
  end

  # GET /order_lines/new
  def new
    @order_line = OrderLine.new
  end

  # GET /order_lines/1/edit
  def edit
  end

  # POST /order_lines
  # POST /order_lines.json
  def create
    @order_line = OrderLine.new(order_line_params)

    respond_to do |format|
      if @order_line.save
        format.html { redirect_to @order_line, notice: 'Order line was successfully created.' }
        format.json { render :show, status: :created, location: @order_line }
      else
        format.html { render :new }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_lines/1
  # PATCH/PUT /order_lines/1.json
  def update
    respond_to do |format|
      if @order_line.update(order_line_params)
        format.html { redirect_to @order_line, notice: 'Order line was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_line }
      else
        format.html { render :edit }
        format.json { render json: @order_line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_lines/1
  # DELETE /order_lines/1.json
  def destroy
    @order_line.destroy
    respond_to do |format|
      format.html { redirect_to order_lines_url, notice: 'Order line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_line
      @order_line = OrderLine.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_line_params
      params.require(:order_line).permit(:order_id, :product_id, :quantity_id)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :table_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/modifiers_helper.rb
module ModifiersHelper
end

app/helpers/order_audits_helper.rb
module OrderAuditsHelper
end

app/helpers/order_lines_helper.rb
module OrderLinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/order_lines/_form.html.erb
<%= form_for(@order_line) do |f| %>
  <% if @order_line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_line.errors.count, "error") %> prohibited this order_line from being saved:</h2>

      <ul>
      <% @order_line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.text_field :order_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity_id %><br>
    <%= f.text_field :quantity_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_lines/edit.html.erb
<h1>Editing Order Line</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_line %> |
<%= link_to 'Back', order_lines_path %>

app/views/order_lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Lines</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Product</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_lines.each do |order_line| %>
      <tr>
        <td><%= order_line.order %></td>
        <td><%= order_line.product %></td>
        <td><%= order_line.quantity %></td>
        <td><%= link_to 'Show', order_line %></td>
        <td><%= link_to 'Edit', edit_order_line_path(order_line) %></td>
        <td><%= link_to 'Destroy', order_line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order line', new_order_line_path %>

app/views/order_lines/new.html.erb
<h1>New Order Line</h1>

<%= render 'form' %>

<%= link_to 'Back', order_lines_path %>

app/views/order_lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @order_line.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @order_line.product %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order_line.quantity %>
</p>

<%= link_to 'Edit', edit_order_line_path(@order_line) %> |
<%= link_to 'Back', order_lines_path %>